server:
  port: 9001


spring:
  application:
    name: DEPARTMENT-SERVICE


  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
#    config:
#      enabled: true
#      uri: http://localhost:9296

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true